// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Page documents */
interface PageDocumentData {
    /**
     * Slice Zone field in *Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<PageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Page → Slice Zone*
 *
 */
type PageDocumentDataSlicesSlice = TitleSubtitleCtaSlice | LeftTextRightImageSlice | TitleWithRepeatableTextImageSlice | TitleSubtitleWithRepeatableTabSwitchSlice | TeamSlice | LogoSliderSlice | FaqSlice | DownloadFreeTaxGuideSlice;
/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;
/** Content for Team Member documents */
interface TeamMemberDocumentData {
    /**
     * Profile Image field in *Team Member*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: team_member.profile_image
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    profile_image: prismicT.ImageField<never>;
    /**
     * Name field in *Team Member*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: team_member.name
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name: prismicT.KeyTextField;
    /**
     * Designation field in *Team Member*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: team_member.designation
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    designation: prismicT.KeyTextField;
    /**
     * Select Team Category field in *Team Member*
     *
     * - **Field Type**: Content Relationship
     * - **Placeholder**: *None*
     * - **API ID Path**: team_member.select_team_category
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    select_team_category: prismicT.RelationField<"teamcategroy">;
}
/**
 * Team Member document from Prismic
 *
 * - **API ID**: `team_member`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeamMemberDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<TeamMemberDocumentData>, "team_member", Lang>;
/** Content for TeamCategroy documents */
interface TeamcategroyDocumentData {
    /**
     * Team Category Title field in *TeamCategroy*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: teamcategroy.team_category_title
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    team_category_title: prismicT.KeyTextField;
}
/**
 * TeamCategroy document from Prismic
 *
 * - **API ID**: `teamcategroy`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TeamcategroyDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<TeamcategroyDocumentData>, "teamcategroy", Lang>;
export type AllDocumentTypes = PageDocument | TeamMemberDocument | TeamcategroyDocument;
/**
 * Primary content in DownloadFreeTaxGuide → Primary
 *
 */
interface DownloadFreeTaxGuideSliceDefaultPrimary {
    /**
     * Title field in *DownloadFreeTaxGuide → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: download_free_tax_guide.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Name Placeholder field in *DownloadFreeTaxGuide → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: download_free_tax_guide.primary.name_placeholder
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name_placeholder: prismicT.KeyTextField;
    /**
     * Name Error Text field in *DownloadFreeTaxGuide → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: download_free_tax_guide.primary.name_error_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    name_error_text: prismicT.KeyTextField;
    /**
     * Email Placeholder field in *DownloadFreeTaxGuide → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: download_free_tax_guide.primary.email_placeholder
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    email_placeholder: prismicT.KeyTextField;
    /**
     * Email Error Text field in *DownloadFreeTaxGuide → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: download_free_tax_guide.primary.email_error_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    email_error_text: prismicT.KeyTextField;
    /**
     * CTA Label field in *DownloadFreeTaxGuide → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: download_free_tax_guide.primary.cta_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    cta_label: prismicT.KeyTextField;
    /**
     * Error Text field in *DownloadFreeTaxGuide → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: download_free_tax_guide.primary.error_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    error_text: prismicT.KeyTextField;
    /**
     * Success Text field in *DownloadFreeTaxGuide → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: download_free_tax_guide.primary.success_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    success_text: prismicT.KeyTextField;
}
/**
 * Default variation for DownloadFreeTaxGuide Slice
 *
 * - **API ID**: `default`
 * - **Description**: `DownloadFreeTaxGuide`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DownloadFreeTaxGuideSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<DownloadFreeTaxGuideSliceDefaultPrimary>, never>;
/**
 * Slice variation for *DownloadFreeTaxGuide*
 *
 */
type DownloadFreeTaxGuideSliceVariation = DownloadFreeTaxGuideSliceDefault;
/**
 * DownloadFreeTaxGuide Shared Slice
 *
 * - **API ID**: `download_free_tax_guide`
 * - **Description**: `DownloadFreeTaxGuide`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type DownloadFreeTaxGuideSlice = prismicT.SharedSlice<"download_free_tax_guide", DownloadFreeTaxGuideSliceVariation>;
/**
 * Primary content in Faq → Primary
 *
 */
interface FaqSliceDefaultPrimary {
    /**
     * Title field in *Faq → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: faq.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
}
/**
 * Item in Faq → Items
 *
 */
export interface FaqSliceDefaultItem {
    /**
     * Question field in *Faq → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: faq.items[].question
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    question: prismicT.KeyTextField;
    /**
     * Answer field in *Faq → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: faq.items[].answer
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    answer: prismicT.RichTextField;
}
/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Faq`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FaqSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<FaqSliceDefaultPrimary>, Simplify<FaqSliceDefaultItem>>;
/**
 * Slice variation for *Faq*
 *
 */
type FaqSliceVariation = FaqSliceDefault;
/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: `Faq`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FaqSlice = prismicT.SharedSlice<"faq", FaqSliceVariation>;
/**
 * Primary content in LeftTextRightImage → Primary
 *
 */
interface LeftTextRightImageSliceDefaultPrimary {
    /**
     * Title field in *LeftTextRightImage → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: left_text_right_image.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Subtitle field in *LeftTextRightImage → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: left_text_right_image.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    subtitle: prismicT.KeyTextField;
    /**
     * FeaturedImage field in *LeftTextRightImage → Primary*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: left_text_right_image.primary.featuredimage
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    featuredimage: prismicT.ImageField<never>;
}
/**
 * Default variation for LeftTextRightImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: `LeftTextRightImage`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LeftTextRightImageSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<LeftTextRightImageSliceDefaultPrimary>, never>;
/**
 * Slice variation for *LeftTextRightImage*
 *
 */
type LeftTextRightImageSliceVariation = LeftTextRightImageSliceDefault;
/**
 * LeftTextRightImage Shared Slice
 *
 * - **API ID**: `left_text_right_image`
 * - **Description**: `LeftTextRightImage`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LeftTextRightImageSlice = prismicT.SharedSlice<"left_text_right_image", LeftTextRightImageSliceVariation>;
/**
 * Primary content in LogoSlider → Primary
 *
 */
interface LogoSliderSliceDefaultPrimary {
    /**
     * Title field in *LogoSlider → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: logo_slider.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
}
/**
 * Item in LogoSlider → Items
 *
 */
export interface LogoSliderSliceDefaultItem {
    /**
     * Logo field in *LogoSlider → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: logo_slider.items[].logo
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    logo: prismicT.ImageField<never>;
}
/**
 * Default variation for LogoSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: `LogoSlider`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LogoSliderSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<LogoSliderSliceDefaultPrimary>, Simplify<LogoSliderSliceDefaultItem>>;
/**
 * Slice variation for *LogoSlider*
 *
 */
type LogoSliderSliceVariation = LogoSliderSliceDefault;
/**
 * LogoSlider Shared Slice
 *
 * - **API ID**: `logo_slider`
 * - **Description**: `LogoSlider`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type LogoSliderSlice = prismicT.SharedSlice<"logo_slider", LogoSliderSliceVariation>;
/**
 * Default variation for Team Slice
 *
 * - **API ID**: `default`
 * - **Description**: `Team`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TeamSliceDefault = prismicT.SharedSliceVariation<"default", Record<string, never>, never>;
/**
 * Slice variation for *Team*
 *
 */
type TeamSliceVariation = TeamSliceDefault;
/**
 * Team Shared Slice
 *
 * - **API ID**: `team`
 * - **Description**: `Team`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TeamSlice = prismicT.SharedSlice<"team", TeamSliceVariation>;
/**
 * Primary content in TitleSubtitleCta → Primary
 *
 */
interface TitleSubtitleCtaSliceDefaultPrimary {
    /**
     * Title field in *TitleSubtitleCta → Primary*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_subtitle_cta.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.RichTextField;
    /**
     * Subtitle field in *TitleSubtitleCta → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_subtitle_cta.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    subtitle: prismicT.KeyTextField;
    /**
     * CTA Link field in *TitleSubtitleCta → Primary*
     *
     * - **Field Type**: Link
     * - **Placeholder**: *None*
     * - **API ID Path**: title_subtitle_cta.primary.cta_link
     * - **Documentation**: https://prismic.io/docs/core-concepts/link-content-relationship
     *
     */
    cta_link: prismicT.LinkField;
    /**
     * CTA Label field in *TitleSubtitleCta → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_subtitle_cta.primary.cta_label
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    cta_label: prismicT.KeyTextField;
}
/**
 * Default variation for TitleSubtitleCta Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TitleSubtitleCta`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TitleSubtitleCtaSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TitleSubtitleCtaSliceDefaultPrimary>, never>;
/**
 * Slice variation for *TitleSubtitleCta*
 *
 */
type TitleSubtitleCtaSliceVariation = TitleSubtitleCtaSliceDefault;
/**
 * TitleSubtitleCta Shared Slice
 *
 * - **API ID**: `title_subtitle_cta`
 * - **Description**: `TitleSubtitleCta`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TitleSubtitleCtaSlice = prismicT.SharedSlice<"title_subtitle_cta", TitleSubtitleCtaSliceVariation>;
/**
 * Primary content in TitleSubtitleWithRepeatableTabSwitch → Primary
 *
 */
interface TitleSubtitleWithRepeatableTabSwitchSliceDefaultPrimary {
    /**
     * Title field in *TitleSubtitleWithRepeatableTabSwitch → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_subtitle_with_repeatable_tab_switch.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
    /**
     * Subtitle field in *TitleSubtitleWithRepeatableTabSwitch → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_subtitle_with_repeatable_tab_switch.primary.subtitle
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    subtitle: prismicT.KeyTextField;
}
/**
 * Item in TitleSubtitleWithRepeatableTabSwitch → Items
 *
 */
export interface TitleSubtitleWithRepeatableTabSwitchSliceDefaultItem {
    /**
     * Tab Text field in *TitleSubtitleWithRepeatableTabSwitch → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_subtitle_with_repeatable_tab_switch.items[].tab_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    tab_text: prismicT.KeyTextField;
    /**
     * Featured Image field in *TitleSubtitleWithRepeatableTabSwitch → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: title_subtitle_with_repeatable_tab_switch.items[].featured_image
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    featured_image: prismicT.ImageField<never>;
    /**
     * Featured Image Text field in *TitleSubtitleWithRepeatableTabSwitch → Items*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_subtitle_with_repeatable_tab_switch.items[].featured_image_text
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    featured_image_text: prismicT.KeyTextField;
}
/**
 * Default variation for TitleSubtitleWithRepeatableTabSwitch Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TitleSubtitleWithRepeatableTabSwitch`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TitleSubtitleWithRepeatableTabSwitchSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TitleSubtitleWithRepeatableTabSwitchSliceDefaultPrimary>, Simplify<TitleSubtitleWithRepeatableTabSwitchSliceDefaultItem>>;
/**
 * Slice variation for *TitleSubtitleWithRepeatableTabSwitch*
 *
 */
type TitleSubtitleWithRepeatableTabSwitchSliceVariation = TitleSubtitleWithRepeatableTabSwitchSliceDefault;
/**
 * TitleSubtitleWithRepeatableTabSwitch Shared Slice
 *
 * - **API ID**: `title_subtitle_with_repeatable_tab_switch`
 * - **Description**: `TitleSubtitleWithRepeatableTabSwitch`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TitleSubtitleWithRepeatableTabSwitchSlice = prismicT.SharedSlice<"title_subtitle_with_repeatable_tab_switch", TitleSubtitleWithRepeatableTabSwitchSliceVariation>;
/**
 * Primary content in TitleWithRepeatableTextImage → Primary
 *
 */
interface TitleWithRepeatableTextImageSliceDefaultPrimary {
    /**
     * Title field in *TitleWithRepeatableTextImage → Primary*
     *
     * - **Field Type**: Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_with_repeatable_text_image.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/key-text
     *
     */
    title: prismicT.KeyTextField;
}
/**
 * Item in TitleWithRepeatableTextImage → Items
 *
 */
export interface TitleWithRepeatableTextImageSliceDefaultItem {
    /**
     * FeaturedImage field in *TitleWithRepeatableTextImage → Items*
     *
     * - **Field Type**: Image
     * - **Placeholder**: *None*
     * - **API ID Path**: title_with_repeatable_text_image.items[].featuredimage
     * - **Documentation**: https://prismic.io/docs/core-concepts/image
     *
     */
    featuredimage: prismicT.ImageField<never>;
    /**
     * Rich Text field in *TitleWithRepeatableTextImage → Items*
     *
     * - **Field Type**: Rich Text
     * - **Placeholder**: *None*
     * - **API ID Path**: title_with_repeatable_text_image.items[].richText
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    richText: prismicT.RichTextField;
}
/**
 * Default variation for TitleWithRepeatableTextImage Slice
 *
 * - **API ID**: `default`
 * - **Description**: `TitleWithRepeatableTextImage`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TitleWithRepeatableTextImageSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<TitleWithRepeatableTextImageSliceDefaultPrimary>, Simplify<TitleWithRepeatableTextImageSliceDefaultItem>>;
/**
 * Slice variation for *TitleWithRepeatableTextImage*
 *
 */
type TitleWithRepeatableTextImageSliceVariation = TitleWithRepeatableTextImageSliceDefault;
/**
 * TitleWithRepeatableTextImage Shared Slice
 *
 * - **API ID**: `title_with_repeatable_text_image`
 * - **Description**: `TitleWithRepeatableTextImage`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type TitleWithRepeatableTextImageSlice = prismicT.SharedSlice<"title_with_repeatable_text_image", TitleWithRepeatableTextImageSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { PageDocumentData, PageDocumentDataSlicesSlice, PageDocument, TeamMemberDocumentData, TeamMemberDocument, TeamcategroyDocumentData, TeamcategroyDocument, AllDocumentTypes, DownloadFreeTaxGuideSliceDefaultPrimary, DownloadFreeTaxGuideSliceDefault, DownloadFreeTaxGuideSliceVariation, DownloadFreeTaxGuideSlice, FaqSliceDefaultPrimary, FaqSliceDefaultItem, FaqSliceDefault, FaqSliceVariation, FaqSlice, LeftTextRightImageSliceDefaultPrimary, LeftTextRightImageSliceDefault, LeftTextRightImageSliceVariation, LeftTextRightImageSlice, LogoSliderSliceDefaultPrimary, LogoSliderSliceDefaultItem, LogoSliderSliceDefault, LogoSliderSliceVariation, LogoSliderSlice, TeamSliceDefault, TeamSliceVariation, TeamSlice, TitleSubtitleCtaSliceDefaultPrimary, TitleSubtitleCtaSliceDefault, TitleSubtitleCtaSliceVariation, TitleSubtitleCtaSlice, TitleSubtitleWithRepeatableTabSwitchSliceDefaultPrimary, TitleSubtitleWithRepeatableTabSwitchSliceDefaultItem, TitleSubtitleWithRepeatableTabSwitchSliceDefault, TitleSubtitleWithRepeatableTabSwitchSliceVariation, TitleSubtitleWithRepeatableTabSwitchSlice, TitleWithRepeatableTextImageSliceDefaultPrimary, TitleWithRepeatableTextImageSliceDefaultItem, TitleWithRepeatableTextImageSliceDefault, TitleWithRepeatableTextImageSliceVariation, TitleWithRepeatableTextImageSlice };
    }
}
