// Code generated by Slice Machine. DO NOT EDIT.

import DownloadFreeTaxGuide from './DownloadFreeTaxGuide';
import Faq from './Faq';
import LeftTextRightImage from './LeftTextRightImage';
import LogoSlider from './LogoSlider';
import Team from './Team';
import TitleSubtitleCta from './TitleSubtitleCta';
import TitleSubtitleWithRepeatableTabSwitch from './TitleSubtitleWithRepeatableTabSwitch';
import TitleWithRepeatableTextImage from './TitleWithRepeatableTextImage';

export {
	DownloadFreeTaxGuide,
	Faq,
	LeftTextRightImage,
	LogoSlider,
	Team,
	TitleSubtitleCta,
	TitleSubtitleWithRepeatableTabSwitch,
	TitleWithRepeatableTextImage,
};

export const components = {
	download_free_tax_guide: DownloadFreeTaxGuide,
	faq: Faq,
	left_text_right_image: LeftTextRightImage,
	logo_slider: LogoSlider,
	team: Team,
	title_subtitle_cta: TitleSubtitleCta,
	title_subtitle_with_repeatable_tab_switch: TitleSubtitleWithRepeatableTabSwitch,
	title_with_repeatable_text_image: TitleWithRepeatableTextImage,
};
