const states = [
  { value: "AN", name: "Andaman and Nicobar Islands", id: 1 },
  { value: "AP", name: "Andhra Pradesh", id: 2 },
  { value: "AR", name: "Arunachal Pradesh", id: 3 },
  { value: "AS", name: "Assam", id: 4 },
  { value: "BR", name: "Bihar", id: 5 },
  { value: "CH", name: "Chandigarh", id: 6 },
  { value: "CT", name: "Chhattisgarh", id: 7 },
  { value: "DN", name: "Dadra and Nagar Haveli", id: 8 },
  { value: "DD", name: "Daman and Diu", id: 9 },
  { value: "DL", name: "Delhi", id: 10 },
  { value: "GA", name: "Goa", id: 11 },
  { value: "GJ", name: "Gujarat", id: 12 },
  { value: "HR", name: "Haryana", id: 13 },
  { value: "HP", name: "Himachal Pradesh", id: 14 },
  { value: "JK", name: "Jammu and Kashmir", id: 15 },
  { value: "JH", name: "Jharkhand", id: 16 },
  { value: "KA", name: "Karnataka", id: 17 },
  { value: "KL", name: "Kerala", id: 18 },
  { value: "LA", name: "Ladakh", id: 19 },
  { value: "LD", name: "Lakshadweep", id: 20 },
  { value: "MP", name: "Madhya Pradesh", id: 21 },
  { value: "MH", name: "Maharashtra", id: 22 },
  { value: "MN", name: "Manipur", id: 23 },
  { value: "ML", name: "Meghalaya", id: 24 },
  { value: "MZ", name: "Mizoram", id: 25 },
  { value: "NL", name: "Nagaland", id: 26 },
  { value: "OR", name: "Odisha", id: 27 },
  { value: "PY", name: "Puducherry", id: 28 },
  { value: "PB", name: "Punjab", id: 29 },
  { value: "RJ", name: "Rajasthan", id: 30 },
  { value: "SK", name: "Sikkim", id: 31 },
  { value: "TN", name: "Tamil Nadu", id: 32 },
  { value: "TG", name: "Telangana", id: 33 },
  { value: "TR", name: "Tripura", id: 34 },
  { value: "UP", name: "Uttar Pradesh", id: 35 },
  { value: "UT", name: "Uttarakhand", id: 36 },
  { value: "WB", name: "West Bengal", id: 37 },
];

export default states;
