import mongoose from "mongoose";
const ObjectId = mongoose.Schema.Types.ObjectId;

const schema = new mongoose.Schema(
  {
    txnid: { type: String, required: true, unique: true },
    amount: String,
    productinfo: String,
    firstname: String,
    email: { type: String, required: true },
    phone: Number,
    mihpayid: String,
    mode: String,
    status: String,
    unmappedstatus: String,
    cardCategory: String,
    discount: String,
    net_amount_debit: String,
    addedon: String,
    lastname: String,
    address1: String,
    address2: String,
    city: String,
    state: String,
    country: String,
    zipcode: String,
    udf1: String,
    udf2: String,
    udf3: String,
    udf4: String,
    udf5: String,
    udf6: String,
    udf7: String,
    udf8: String,
    udf9: String,
    udf10: String,
    hash: String,
    field1: String,
    field2: String,
    field3: String,
    field4: String,
    field5: String,
    field6: String,
    field7: String,
    field8: String,
    field9: String,
    payment_source: String,
    PG_TYPE: String,
    bank_ref_num: String,
    bankcode: String,
    error: String,
    error_Message: String,
    name_on_card: String,
    cardnum: String,
    cardhash: String,
    confirmed_status: { default: null, type: Boolean },
  },
  {
    timestamps: {
      createdAt: "created_at",
      updatedAt: "updated_at",
    },
    versionKey: false,
  }
);

export default mongoose.models.payment || mongoose.model("payment", schema);
